C19/c22 新增彈窗靜態頁面
Kim716/ac_twitter pull request #16
Opened 2023-03-24 11:14 UTC by violet120

[演示影片](https://youtu.be/2VP4W9EqUzc)
新增兩個靜態彈窗頁，測試回覆內容或推文內容輸入到最大字數是否跑版。

2023-03-24 11:27 UTC, Kim716 requested changes
切 modal 辛苦了

2023-03-24 11:27 UTC, Kim716 commented on src/components/containers/ModalContainer.jsx
> +  background-color: var(--gray4);
彈窗的背景應該要是半透明的黑色

2023-03-24 11:27 UTC, Kim716 commented on src/components/containers/ModalContainer.jsx
> +  background-color: var(--gray4);
另外從影片看到的是：
1. 沒看到第二個 modal 跳提示
2. 照片可能要根據假資料去切初固定的圓，因為使用者上傳的照片大小都不一樣

2023-03-24 13:09 UTC, violet120 commented on src/components/containers/ModalContainer.jsx
> +  background-color: var(--gray4);
調整透明度，並把第二個跳提示的內容補上。(後續按鈕互動功能寫好後，就可以選擇讓字體依照狀態出現)
照片的部分有切一個固定圓形的CSS，在img內有 border-radius: 50%; 語法。

2023-03-24 14:05 UTC, Kim716 requested changes
線上講解～

2023-03-24 14:10 UTC, Kim716 approved these changes
OK，有線上核對

2023-03-24 14:11 UTC, merged

2023-03-25 02:03 UTC, violet120 commented on src/components/containers/ModalContainer.jsx
> +// 筆記：按鈕串接時，要傳入一個參數進來控制顯示的彈窗。
還要想一下更完整的寫法，所以開新分支將編輯個人資料彈窗切完後，一併寫互動設計。